spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/pigeonSkyRace?connectTimeoutMS=30000
      authentication-database: admin
      username: admin
      password: admin
      database: pigeonSkyRace
      port: 27017
      host: mongodb
